/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/icomore.glb -o src/components/Icomore.jsx -r public -k 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useExplode } from "../../hooks/useExplode";

export function Icomore(props) {
  const { nodes, materials } = useGLTF("/models/icomore.glb");
  const group = useRef();

  useExplode(group, {
    distance: 1,
  });

  return (
    <group {...props} dispose={null} ref={group} castShadow>
      <group name="Platonic_fracturepart1" position={[0.449, 0.493, -0.097]}>
        <mesh
          name="Platonic_fracturepart1_1"
          geometry={nodes.Platonic_fracturepart1_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart1_2"
          geometry={nodes.Platonic_fracturepart1_2.geometry}
          material={materials["Mat.1"] }
        />
      </group>
      <mesh
        name="Platonic_fracturepart10"
        geometry={nodes.Platonic_fracturepart10.geometry}
        material={materials["Mat.1"]}
        position={[-0.553, -0.121, -0.329]}
      />
      <group
        name="Platonic_fracturepart100"
        position={[-0.655, -0.227, -0.189]}
      >
        <mesh
          name="Platonic_fracturepart100_1"
          geometry={nodes.Platonic_fracturepart100_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart100_2"
          geometry={nodes.Platonic_fracturepart100_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart101"
        geometry={nodes.Platonic_fracturepart101.geometry}
        material={materials["Mat.1"]}
        position={[-0.256, 0.234, -0.435]}
      />
      <group name="Platonic_fracturepart102" position={[-0.355, -0.61, -0.042]}>
        <mesh
          name="Platonic_fracturepart102_1"
          geometry={nodes.Platonic_fracturepart102_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart102_2"
          geometry={nodes.Platonic_fracturepart102_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group
        name="Platonic_fracturepart103"
        position={[-0.725, -0.147, -0.086]}
      >
        <mesh
          name="Platonic_fracturepart103_1"
          geometry={nodes.Platonic_fracturepart103_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart103_2"
          geometry={nodes.Platonic_fracturepart103_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart104" position={[-0.749, 0.203, -0.173]}>
        <mesh
          name="Platonic_fracturepart104_1"
          geometry={nodes.Platonic_fracturepart104_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart104_2"
          geometry={nodes.Platonic_fracturepart104_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart105"
        geometry={nodes.Platonic_fracturepart105.geometry}
        material={materials["Mat.1"]}
        position={[-0.464, 0.475, 0.094]}
      />
      <group name="Platonic_fracturepart106" position={[-0.684, 0.194, 0.502]}>
        <mesh
          name="Platonic_fracturepart106_1"
          geometry={nodes.Platonic_fracturepart106_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart106_2"
          geometry={nodes.Platonic_fracturepart106_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart107" position={[-0.77, 0.041, -0.455]}>
        <mesh
          name="Platonic_fracturepart107_1"
          geometry={nodes.Platonic_fracturepart107_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart107_2"
          geometry={nodes.Platonic_fracturepart107_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart108" position={[-0.773, 0.071, -0.333]}>
        <mesh
          name="Platonic_fracturepart108_1"
          geometry={nodes.Platonic_fracturepart108_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart108_2"
          geometry={nodes.Platonic_fracturepart108_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group
        name="Platonic_fracturepart109"
        position={[-0.642, -0.316, -0.126]}
      >
        <mesh
          name="Platonic_fracturepart109_1"
          geometry={nodes.Platonic_fracturepart109_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart109_2"
          geometry={nodes.Platonic_fracturepart109_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart11"
        geometry={nodes.Platonic_fracturepart11.geometry}
        material={materials["Mat.1"]}
        position={[-0.573, -0.164, -0.237]}
      />
      <mesh
        name="Platonic_fracturepart110"
        geometry={nodes.Platonic_fracturepart110.geometry}
        material={materials["Mat.1"]}
        position={[-0.045, 0.365, -0.456]}
      />
      <group
        name="Platonic_fracturepart111"
        position={[-0.536, -0.108, -0.498]}
      >
        <mesh
          name="Platonic_fracturepart111_1"
          geometry={nodes.Platonic_fracturepart111_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart111_2"
          geometry={nodes.Platonic_fracturepart111_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart112"
        geometry={nodes.Platonic_fracturepart112.geometry}
        material={materials["Mat.1"]}
        position={[-0.346, -0.047, -0.199]}
      />
      <group name="Platonic_fracturepart113" position={[-0.66, -0.298, 0.021]}>
        <mesh
          name="Platonic_fracturepart113_1"
          geometry={nodes.Platonic_fracturepart113_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart113_2"
          geometry={nodes.Platonic_fracturepart113_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart114" position={[-0.793, 0.055, 0.009]}>
        <mesh
          name="Platonic_fracturepart114_1"
          geometry={nodes.Platonic_fracturepart114_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart114_2"
          geometry={nodes.Platonic_fracturepart114_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart115" position={[-0.444, -0.207, 0.628]}>
        <mesh
          name="Platonic_fracturepart115_1"
          geometry={nodes.Platonic_fracturepart115_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart115_2"
          geometry={nodes.Platonic_fracturepart115_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group
        name="Platonic_fracturepart116"
        position={[-0.564, -0.409, -0.074]}
      >
        <mesh
          name="Platonic_fracturepart116_1"
          geometry={nodes.Platonic_fracturepart116_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart116_2"
          geometry={nodes.Platonic_fracturepart116_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart117"
        geometry={nodes.Platonic_fracturepart117.geometry}
        material={materials["Mat.1"]}
        position={[-0.189, -0.356, 0.389]}
      />
      <group name="Platonic_fracturepart118" position={[-0.185, 0.59, -0.073]}>
        <mesh
          name="Platonic_fracturepart118_1"
          geometry={nodes.Platonic_fracturepart118_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart118_2"
          geometry={nodes.Platonic_fracturepart118_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart119" position={[-0.675, 0.419, 0.198]}>
        <mesh
          name="Platonic_fracturepart119_1"
          geometry={nodes.Platonic_fracturepart119_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart119_2"
          geometry={nodes.Platonic_fracturepart119_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart12" position={[0.581, -0.318, 0.07]}>
        <mesh
          name="Platonic_fracturepart12_1"
          geometry={nodes.Platonic_fracturepart12_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart12_2"
          geometry={nodes.Platonic_fracturepart12_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart120"
        geometry={nodes.Platonic_fracturepart120.geometry}
        material={materials["Mat.1"]}
        position={[-0.289, -0.468, 0.102]}
      />
      <mesh
        name="Platonic_fracturepart121"
        geometry={nodes.Platonic_fracturepart121.geometry}
        material={materials["Mat.1"]}
        position={[-0.147, -0.105, -0.393]}
      />
      <mesh
        name="Platonic_fracturepart122"
        geometry={nodes.Platonic_fracturepart122.geometry}
        material={materials["Mat.1"]}
        position={[-0.722, 0.016, 0.062]}
      />
      <mesh
        name="Platonic_fracturepart123"
        geometry={nodes.Platonic_fracturepart123.geometry}
        material={materials["Mat.1"]}
        position={[-0.053, -0.462, -0.026]}
      />
      <mesh
        name="Platonic_fracturepart124"
        geometry={nodes.Platonic_fracturepart124.geometry}
        material={materials["Mat.1"]}
        position={[-0.237, 0.007, 0.07]}
      />
      <group
        name="Platonic_fracturepart125"
        position={[-0.405, -0.357, -0.589]}
      >
        <mesh
          name="Platonic_fracturepart125_1"
          geometry={nodes.Platonic_fracturepart125_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart125_2"
          geometry={nodes.Platonic_fracturepart125_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart126"
        geometry={nodes.Platonic_fracturepart126.geometry}
        material={materials["Mat.1"]}
        position={[-0.423, -0.039, -0.302]}
      />
      <group name="Platonic_fracturepart127" position={[-0.337, 0.425, -0.567]}>
        <mesh
          name="Platonic_fracturepart127_1"
          geometry={nodes.Platonic_fracturepart127_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart127_2"
          geometry={nodes.Platonic_fracturepart127_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart128" position={[-0.669, -0.144, 0.403]}>
        <mesh
          name="Platonic_fracturepart128_1"
          geometry={nodes.Platonic_fracturepart128_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart128_2"
          geometry={nodes.Platonic_fracturepart128_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart129" position={[-0.644, 0.328, -0.117]}>
        <mesh
          name="Platonic_fracturepart129_1"
          geometry={nodes.Platonic_fracturepart129_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart129_2"
          geometry={nodes.Platonic_fracturepart129_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart13"
        geometry={nodes.Platonic_fracturepart13.geometry}
        material={materials["Mat.1"]}
        position={[-0.35, -0.062, 0.389]}
      />
      <group name="Platonic_fracturepart130" position={[0.027, -0.648, -0.213]}>
        <mesh
          name="Platonic_fracturepart130_1"
          geometry={nodes.Platonic_fracturepart130_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart130_2"
          geometry={nodes.Platonic_fracturepart130_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart131"
        geometry={nodes.Platonic_fracturepart131.geometry}
        material={materials["Mat.1"]}
        position={[-0.559, -0.119, -0.175]}
      />
      <mesh
        name="Platonic_fracturepart132"
        geometry={nodes.Platonic_fracturepart132.geometry}
        material={materials["Mat.1"]}
        position={[-0.394, -0.097, 0.164]}
      />
      <group name="Platonic_fracturepart133" position={[-0.274, 0.531, -0.334]}>
        <mesh
          name="Platonic_fracturepart133_1"
          geometry={nodes.Platonic_fracturepart133_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart133_2"
          geometry={nodes.Platonic_fracturepart133_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart134" position={[-0.632, 0.36, 0.073]}>
        <mesh
          name="Platonic_fracturepart134_1"
          geometry={nodes.Platonic_fracturepart134_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart134_2"
          geometry={nodes.Platonic_fracturepart134_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart135" position={[-0.707, -0.206, 0.343]}>
        <mesh
          name="Platonic_fracturepart135_1"
          geometry={nodes.Platonic_fracturepart135_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart135_2"
          geometry={nodes.Platonic_fracturepart135_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart136"
        geometry={nodes.Platonic_fracturepart136.geometry}
        material={materials["Mat.1"]}
        position={[-0.656, -0.004, 0.299]}
      />
      <group name="Platonic_fracturepart137" position={[-0.685, -0.078, -0.42]}>
        <mesh
          name="Platonic_fracturepart137_1"
          geometry={nodes.Platonic_fracturepart137_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart137_2"
          geometry={nodes.Platonic_fracturepart137_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart138" position={[-0.414, 0.723, -0.121]}>
        <mesh
          name="Platonic_fracturepart138_1"
          geometry={nodes.Platonic_fracturepart138_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart138_2"
          geometry={nodes.Platonic_fracturepart138_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart139"
        geometry={nodes.Platonic_fracturepart139.geometry}
        material={materials["Mat.1"]}
        position={[-0.283, -0.291, 0.238]}
      />
      <mesh
        name="Platonic_fracturepart14"
        geometry={nodes.Platonic_fracturepart14.geometry}
        material={materials["Mat.1"]}
        position={[-0.33, -0.345, -0.181]}
      />
      <group name="Platonic_fracturepart140" position={[0.482, 0.02, -0.276]}>
        <mesh
          name="Platonic_fracturepart140_1"
          geometry={nodes.Platonic_fracturepart140_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart140_2"
          geometry={nodes.Platonic_fracturepart140_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart141" position={[0.014, -0.61, 0.356]}>
        <mesh
          name="Platonic_fracturepart141_1"
          geometry={nodes.Platonic_fracturepart141_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart141_2"
          geometry={nodes.Platonic_fracturepart141_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart142"
        geometry={nodes.Platonic_fracturepart142.geometry}
        material={materials["Mat.1"]}
        position={[-0.206, 0.217, -0.385]}
      />
      <group name="Platonic_fracturepart143" position={[-0.253, 0.229, 0.695]}>
        <mesh
          name="Platonic_fracturepart143_1"
          geometry={nodes.Platonic_fracturepart143_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart143_2"
          geometry={nodes.Platonic_fracturepart143_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart144"
        geometry={nodes.Platonic_fracturepart144.geometry}
        material={materials["Mat.1"]}
        position={[-0.267, -0.266, -0.405]}
      />
      <group name="Platonic_fracturepart145" position={[-0.69, -0.015, -0.435]}>
        <mesh
          name="Platonic_fracturepart145_1"
          geometry={nodes.Platonic_fracturepart145_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart145_2"
          geometry={nodes.Platonic_fracturepart145_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart146" position={[-0.088, 0.595, -0.591]}>
        <mesh
          name="Platonic_fracturepart146_1"
          geometry={nodes.Platonic_fracturepart146_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart146_2"
          geometry={nodes.Platonic_fracturepart146_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart147" position={[0.166, 0.578, 0.431]}>
        <mesh
          name="Platonic_fracturepart147_1"
          geometry={nodes.Platonic_fracturepart147_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart147_2"
          geometry={nodes.Platonic_fracturepart147_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart148" position={[-0.514, 0.701, 0.109]}>
        <mesh
          name="Platonic_fracturepart148_1"
          geometry={nodes.Platonic_fracturepart148_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart148_2"
          geometry={nodes.Platonic_fracturepart148_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart149" position={[0.065, 0.617, -0.113]}>
        <mesh
          name="Platonic_fracturepart149_1"
          geometry={nodes.Platonic_fracturepart149_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart149_2"
          geometry={nodes.Platonic_fracturepart149_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart15" position={[-0.205, -0.103, -0.673]}>
        <mesh
          name="Platonic_fracturepart15_1"
          geometry={nodes.Platonic_fracturepart15_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart15_2"
          geometry={nodes.Platonic_fracturepart15_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart150"
        geometry={nodes.Platonic_fracturepart150.geometry}
        material={materials["Mat.1"]}
        position={[0.149, -0.162, 0.151]}
      />
      <mesh
        name="Platonic_fracturepart151"
        geometry={nodes.Platonic_fracturepart151.geometry}
        material={materials["Mat.1"]}
        position={[-0.576, 0.167, -0.205]}
      />
      <group name="Platonic_fracturepart152" position={[0.26, 0.371, 0.425]}>
        <mesh
          name="Platonic_fracturepart152_1"
          geometry={nodes.Platonic_fracturepart152_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart152_2"
          geometry={nodes.Platonic_fracturepart152_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart153" position={[-0.524, -0.487, 0.282]}>
        <mesh
          name="Platonic_fracturepart153_1"
          geometry={nodes.Platonic_fracturepart153_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart153_2"
          geometry={nodes.Platonic_fracturepart153_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart154" position={[-0.653, 0.397, -0.263]}>
        <mesh
          name="Platonic_fracturepart154_1"
          geometry={nodes.Platonic_fracturepart154_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart154_2"
          geometry={nodes.Platonic_fracturepart154_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart155" position={[0.009, -0.17, -0.714]}>
        <mesh
          name="Platonic_fracturepart155_1"
          geometry={nodes.Platonic_fracturepart155_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart155_2"
          geometry={nodes.Platonic_fracturepart155_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart156"
        geometry={nodes.Platonic_fracturepart156.geometry}
        material={materials["Mat.1"]}
        position={[-0.481, 0.002, 0.372]}
      />
      <group name="Platonic_fracturepart157" position={[-0.762, -0.109, 0.122]}>
        <mesh
          name="Platonic_fracturepart157_1"
          geometry={nodes.Platonic_fracturepart157_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart157_2"
          geometry={nodes.Platonic_fracturepart157_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart158" position={[-0.745, 0.038, -0.131]}>
        <mesh
          name="Platonic_fracturepart158_1"
          geometry={nodes.Platonic_fracturepart158_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart158_2"
          geometry={nodes.Platonic_fracturepart158_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart159" position={[-0.628, 0.188, -0.506]}>
        <mesh
          name="Platonic_fracturepart159_1"
          geometry={nodes.Platonic_fracturepart159_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart159_2"
          geometry={nodes.Platonic_fracturepart159_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart16"
        geometry={nodes.Platonic_fracturepart16.geometry}
        material={materials["Mat.1"]}
        position={[-0.076, -0.173, 0.45]}
      />
      <group name="Platonic_fracturepart160" position={[-0.307, -0.144, 0.625]}>
        <mesh
          name="Platonic_fracturepart160_1"
          geometry={nodes.Platonic_fracturepart160_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart160_2"
          geometry={nodes.Platonic_fracturepart160_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group
        name="Platonic_fracturepart161"
        position={[-0.737, -0.019, -0.217]}
      >
        <mesh
          name="Platonic_fracturepart161_1"
          geometry={nodes.Platonic_fracturepart161_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart161_2"
          geometry={nodes.Platonic_fracturepart161_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart162"
        geometry={nodes.Platonic_fracturepart162.geometry}
        material={materials["Mat.1"]}
        position={[-0.539, 0.082, -0.151]}
      />
      <group name="Platonic_fracturepart163" position={[-0.014, 0.599, -0.522]}>
        <mesh
          name="Platonic_fracturepart163_1"
          geometry={nodes.Platonic_fracturepart163_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart163_2"
          geometry={nodes.Platonic_fracturepart163_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart164"
        geometry={nodes.Platonic_fracturepart164.geometry}
        material={materials["Mat.1"]}
        position={[0.121, 0.297, 0.219]}
      />
      <group name="Platonic_fracturepart165" position={[-0.663, -0.175, 0.537]}>
        <mesh
          name="Platonic_fracturepart165_1"
          geometry={nodes.Platonic_fracturepart165_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart165_2"
          geometry={nodes.Platonic_fracturepart165_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart166" position={[0.183, -0.594, 0.177]}>
        <mesh
          name="Platonic_fracturepart166_1"
          geometry={nodes.Platonic_fracturepart166_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart166_2"
          geometry={nodes.Platonic_fracturepart166_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart167" position={[0.334, 0.404, -0.504]}>
        <mesh
          name="Platonic_fracturepart167_1"
          geometry={nodes.Platonic_fracturepart167_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart167_2"
          geometry={nodes.Platonic_fracturepart167_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group
        name="Platonic_fracturepart168"
        position={[-0.591, -0.304, -0.332]}
      >
        <mesh
          name="Platonic_fracturepart168_1"
          geometry={nodes.Platonic_fracturepart168_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart168_2"
          geometry={nodes.Platonic_fracturepart168_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart169" position={[-0.681, -0.306, 0.311]}>
        <mesh
          name="Platonic_fracturepart169_1"
          geometry={nodes.Platonic_fracturepart169_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart169_2"
          geometry={nodes.Platonic_fracturepart169_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart17"
        geometry={nodes.Platonic_fracturepart17.geometry}
        material={materials["Mat.1"]}
        position={[-0.577, 0.097, -0.068]}
      />
      <mesh
        name="Platonic_fracturepart170"
        geometry={nodes.Platonic_fracturepart170.geometry}
        material={materials["Mat.1"]}
        position={[-0.044, -0.363, 0.233]}
      />
      <group name="Platonic_fracturepart171" position={[-0.701, 0.165, -0.019]}>
        <mesh
          name="Platonic_fracturepart171_1"
          geometry={nodes.Platonic_fracturepart171_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart171_2"
          geometry={nodes.Platonic_fracturepart171_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart172"
        geometry={nodes.Platonic_fracturepart172.geometry}
        material={materials["Mat.1"]}
        position={[-0.298, -0.28, 0.001]}
      />
      <group name="Platonic_fracturepart173" position={[-0.635, 0.501, 0.048]}>
        <mesh
          name="Platonic_fracturepart173_1"
          geometry={nodes.Platonic_fracturepart173_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart173_2"
          geometry={nodes.Platonic_fracturepart173_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart174" position={[-0.423, 0.428, -0.504]}>
        <mesh
          name="Platonic_fracturepart174_1"
          geometry={nodes.Platonic_fracturepart174_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart174_2"
          geometry={nodes.Platonic_fracturepart174_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group
        name="Platonic_fracturepart175"
        position={[-0.329, -0.573, -0.363]}
      >
        <mesh
          name="Platonic_fracturepart175_1"
          geometry={nodes.Platonic_fracturepart175_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart175_2"
          geometry={nodes.Platonic_fracturepart175_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart176"
        geometry={nodes.Platonic_fracturepart176.geometry}
        material={materials["Mat.1"]}
        position={[-0.148, 0.12, -0.299]}
      />
      <mesh
        name="Platonic_fracturepart177"
        geometry={nodes.Platonic_fracturepart177.geometry}
        material={materials["Mat.1"]}
        position={[-0.571, 0.23, 0.223]}
      />
      <mesh
        name="Platonic_fracturepart178"
        geometry={nodes.Platonic_fracturepart178.geometry}
        material={materials["Mat.1"]}
        position={[-0.626, -0.11, -0.095]}
      />
      <group name="Platonic_fracturepart179" position={[-0.76, 0.019, 0.138]}>
        <mesh
          name="Platonic_fracturepart179_1"
          geometry={nodes.Platonic_fracturepart179_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart179_2"
          geometry={nodes.Platonic_fracturepart179_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart18" position={[-0.76, -0.162, -0.335]}>
        <mesh
          name="Platonic_fracturepart18_1"
          geometry={nodes.Platonic_fracturepart18_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart18_2"
          geometry={nodes.Platonic_fracturepart18_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart180" position={[-0.652, 0.316, -0.373]}>
        <mesh
          name="Platonic_fracturepart180_1"
          geometry={nodes.Platonic_fracturepart180_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart180_2"
          geometry={nodes.Platonic_fracturepart180_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group
        name="Platonic_fracturepart181"
        position={[-0.096, -0.438, -0.606]}
      >
        <mesh
          name="Platonic_fracturepart181_1"
          geometry={nodes.Platonic_fracturepart181_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart181_2"
          geometry={nodes.Platonic_fracturepart181_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group
        name="Platonic_fracturepart182"
        position={[-0.458, -0.383, -0.477]}
      >
        <mesh
          name="Platonic_fracturepart182_1"
          geometry={nodes.Platonic_fracturepart182_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart182_2"
          geometry={nodes.Platonic_fracturepart182_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart183"
        geometry={nodes.Platonic_fracturepart183.geometry}
        material={materials["Mat.1"]}
        position={[-0.463, -0.33, -0.227]}
      />
      <mesh
        name="Platonic_fracturepart184"
        geometry={nodes.Platonic_fracturepart184.geometry}
        material={materials["Mat.1"]}
        position={[-0.199, 0.018, -0.415]}
      />
      <mesh
        name="Platonic_fracturepart185"
        geometry={nodes.Platonic_fracturepart185.geometry}
        material={materials["Mat.1"]}
        position={[-0.524, -0.059, 0.053]}
      />
      <group name="Platonic_fracturepart186" position={[-0.36, 0.684, -0.256]}>
        <mesh
          name="Platonic_fracturepart186_1"
          geometry={nodes.Platonic_fracturepart186_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart186_2"
          geometry={nodes.Platonic_fracturepart186_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart187"
        geometry={nodes.Platonic_fracturepart187.geometry}
        material={materials["Mat.1"]}
        position={[-0.242, 0.306, 0.16]}
      />
      <group name="Platonic_fracturepart188" position={[-0.717, -0.152, 0.045]}>
        <mesh
          name="Platonic_fracturepart188_1"
          geometry={nodes.Platonic_fracturepart188_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart188_2"
          geometry={nodes.Platonic_fracturepart188_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart189" position={[-0.748, 0.138, 0.255]}>
        <mesh
          name="Platonic_fracturepart189_1"
          geometry={nodes.Platonic_fracturepart189_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart189_2"
          geometry={nodes.Platonic_fracturepart189_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart19" position={[-0.787, -0.07, -0.104]}>
        <mesh
          name="Platonic_fracturepart19_1"
          geometry={nodes.Platonic_fracturepart19_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart19_2"
          geometry={nodes.Platonic_fracturepart19_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart190"
        geometry={nodes.Platonic_fracturepart190.geometry}
        material={materials["Mat.1"]}
        position={[-0.229, -0.261, -0.165]}
      />
      <group name="Platonic_fracturepart191" position={[-0.758, -0.014, 0.419]}>
        <mesh
          name="Platonic_fracturepart191_1"
          geometry={nodes.Platonic_fracturepart191_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart191_2"
          geometry={nodes.Platonic_fracturepart191_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart192"
        geometry={nodes.Platonic_fracturepart192.geometry}
        material={materials["Mat.1"]}
        position={[-0.328, 0.159, 0.126]}
      />
      <mesh
        name="Platonic_fracturepart193"
        geometry={nodes.Platonic_fracturepart193.geometry}
        material={materials["Mat.1"]}
        position={[-0.1, -0.12, 0.243]}
      />
      <group name="Platonic_fracturepart194" position={[-0.085, -0.711, 0.063]}>
        <mesh
          name="Platonic_fracturepart194_1"
          geometry={nodes.Platonic_fracturepart194_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart194_2"
          geometry={nodes.Platonic_fracturepart194_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart195" position={[-0.735, 0.129, -0.208]}>
        <mesh
          name="Platonic_fracturepart195_1"
          geometry={nodes.Platonic_fracturepart195_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart195_2"
          geometry={nodes.Platonic_fracturepart195_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart196" position={[-0.594, 0.198, -0.374]}>
        <mesh
          name="Platonic_fracturepart196_1"
          geometry={nodes.Platonic_fracturepart196_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart196_2"
          geometry={nodes.Platonic_fracturepart196_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart197"
        geometry={nodes.Platonic_fracturepart197.geometry}
        material={materials["Mat.1"]}
        position={[-0.357, 0.064, -0.097]}
      />
      <group name="Platonic_fracturepart198" position={[-0.438, 0.049, -0.541]}>
        <mesh
          name="Platonic_fracturepart198_1"
          geometry={nodes.Platonic_fracturepart198_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart198_2"
          geometry={nodes.Platonic_fracturepart198_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart199"
        geometry={nodes.Platonic_fracturepart199.geometry}
        material={materials["Mat.1"]}
        position={[-0.314, 0.44, 0.281]}
      />
      <mesh
        name="Platonic_fracturepart2"
        geometry={nodes.Platonic_fracturepart2.geometry}
        material={materials["Mat.1"]}
        position={[-0.483, -0.159, 0.444]}
      />
      <group name="Platonic_fracturepart20" position={[0.399, 0.657, -0.139]}>
        <mesh
          name="Platonic_fracturepart20_1"
          geometry={nodes.Platonic_fracturepart20_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart20_2"
          geometry={nodes.Platonic_fracturepart20_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart200" position={[-0.176, 0.647, 0.268]}>
        <mesh
          name="Platonic_fracturepart200_1"
          geometry={nodes.Platonic_fracturepart200_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart200_2"
          geometry={nodes.Platonic_fracturepart200_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart201" position={[-0.176, 0.698, 0.089]}>
        <mesh
          name="Platonic_fracturepart201_1"
          geometry={nodes.Platonic_fracturepart201_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart201_2"
          geometry={nodes.Platonic_fracturepart201_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart202" position={[-0.219, 0.758, -0.019]}>
        <mesh
          name="Platonic_fracturepart202_1"
          geometry={nodes.Platonic_fracturepart202_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart202_2"
          geometry={nodes.Platonic_fracturepart202_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart203" position={[-0.546, 0.428, -0.177]}>
        <mesh
          name="Platonic_fracturepart203_1"
          geometry={nodes.Platonic_fracturepart203_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart203_2"
          geometry={nodes.Platonic_fracturepart203_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart204" position={[-0.712, 0.217, 0.324]}>
        <mesh
          name="Platonic_fracturepart204_1"
          geometry={nodes.Platonic_fracturepart204_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart204_2"
          geometry={nodes.Platonic_fracturepart204_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart205" position={[-0.272, -0.669, 0.312]}>
        <mesh
          name="Platonic_fracturepart205_1"
          geometry={nodes.Platonic_fracturepart205_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart205_2"
          geometry={nodes.Platonic_fracturepart205_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart206"
        geometry={nodes.Platonic_fracturepart206.geometry}
        material={materials["Mat.1"]}
        position={[-0.264, 0.406, -0.012]}
      />
      <group name="Platonic_fracturepart21" position={[-0.492, 0.661, -0.077]}>
        <mesh
          name="Platonic_fracturepart21_1"
          geometry={nodes.Platonic_fracturepart21_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart21_2"
          geometry={nodes.Platonic_fracturepart21_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart22" position={[-0.716, 0.228, 0.02]}>
        <mesh
          name="Platonic_fracturepart22_1"
          geometry={nodes.Platonic_fracturepart22_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart22_2"
          geometry={nodes.Platonic_fracturepart22_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart23" position={[-0.402, -0.18, -0.502]}>
        <mesh
          name="Platonic_fracturepart23_1"
          geometry={nodes.Platonic_fracturepart23_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart23_2"
          geometry={nodes.Platonic_fracturepart23_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart24"
        geometry={nodes.Platonic_fracturepart24.geometry}
        material={materials["Mat.1"]}
        position={[-0.569, 0.06, 0.291]}
      />
      <group name="Platonic_fracturepart25" position={[-0.717, 0.2, 0.213]}>
        <mesh
          name="Platonic_fracturepart25_1"
          geometry={nodes.Platonic_fracturepart25_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart25_2"
          geometry={nodes.Platonic_fracturepart25_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart26"
        geometry={nodes.Platonic_fracturepart26.geometry}
        material={materials["Mat.1"]}
        position={[-0.4, 0.072, 0.542]}
      />
      <group name="Platonic_fracturepart27" position={[-0.034, -0.492, 0.635]}>
        <mesh
          name="Platonic_fracturepart27_1"
          geometry={nodes.Platonic_fracturepart27_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart27_2"
          geometry={nodes.Platonic_fracturepart27_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart28" position={[-0.605, 0.038, 0.539]}>
        <mesh
          name="Platonic_fracturepart28_1"
          geometry={nodes.Platonic_fracturepart28_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart28_2"
          geometry={nodes.Platonic_fracturepart28_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart29" position={[-0.523, -0.566, -0.172]}>
        <mesh
          name="Platonic_fracturepart29_1"
          geometry={nodes.Platonic_fracturepart29_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart29_2"
          geometry={nodes.Platonic_fracturepart29_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart3" position={[-0.496, 0.467, 0.345]}>
        <mesh
          name="Platonic_fracturepart3_1"
          geometry={nodes.Platonic_fracturepart3_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart3_2"
          geometry={nodes.Platonic_fracturepart3_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart30"
        geometry={nodes.Platonic_fracturepart30.geometry}
        material={materials["Mat.1"]}
        position={[-0.62, 0.127, 0.162]}
      />
      <group name="Platonic_fracturepart31" position={[-0.716, 0.228, 0.144]}>
        <mesh
          name="Platonic_fracturepart31_1"
          geometry={nodes.Platonic_fracturepart31_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart31_2"
          geometry={nodes.Platonic_fracturepart31_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart32" position={[-0.452, -0.735, -0.02]}>
        <mesh
          name="Platonic_fracturepart32_1"
          geometry={nodes.Platonic_fracturepart32_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart32_2"
          geometry={nodes.Platonic_fracturepart32_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart33" position={[-0.458, 0.319, 0.538]}>
        <mesh
          name="Platonic_fracturepart33_1"
          geometry={nodes.Platonic_fracturepart33_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart33_2"
          geometry={nodes.Platonic_fracturepart33_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart34" position={[-0.779, -0.061, 0.269]}>
        <mesh
          name="Platonic_fracturepart34_1"
          geometry={nodes.Platonic_fracturepart34_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart34_2"
          geometry={nodes.Platonic_fracturepart34_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart35" position={[-0.703, 0.169, -0.368]}>
        <mesh
          name="Platonic_fracturepart35_1"
          geometry={nodes.Platonic_fracturepart35_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart35_2"
          geometry={nodes.Platonic_fracturepart35_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart36"
        geometry={nodes.Platonic_fracturepart36.geometry}
        material={materials["Mat.1"]}
        position={[-0.457, 0.303, -0.204]}
      />
      <group name="Platonic_fracturepart37" position={[-0.602, -0.216, -0.505]}>
        <mesh
          name="Platonic_fracturepart37_1"
          geometry={nodes.Platonic_fracturepart37_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart37_2"
          geometry={nodes.Platonic_fracturepart37_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart38" position={[0.198, -0.256, 0.625]}>
        <mesh
          name="Platonic_fracturepart38_1"
          geometry={nodes.Platonic_fracturepart38_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart38_2"
          geometry={nodes.Platonic_fracturepart38_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart39"
        geometry={nodes.Platonic_fracturepart39.geometry}
        material={materials["Mat.1"]}
        position={[0.019, -0.297, 0.004]}
      />
      <mesh
        name="Platonic_fracturepart4"
        geometry={nodes.Platonic_fracturepart4.geometry}
        material={materials["Mat.1"]}
        position={[-0.406, -0.123, 0.029]}
      />
      <group name="Platonic_fracturepart40" position={[0.126, 0.267, -0.499]}>
        <mesh
          name="Platonic_fracturepart40_1"
          geometry={nodes.Platonic_fracturepart40_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart40_2"
          geometry={nodes.Platonic_fracturepart40_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart41" position={[-0.3, 0.312, 0.483]}>
        <mesh
          name="Platonic_fracturepart41_1"
          geometry={nodes.Platonic_fracturepart41_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart41_2"
          geometry={nodes.Platonic_fracturepart41_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart42"
        geometry={nodes.Platonic_fracturepart42.geometry}
        material={materials["Mat.1"]}
        position={[-0.153, -0.238, -0.455]}
      />
      <group name="Platonic_fracturepart43" position={[-0.451, 0.051, 0.609]}>
        <mesh
          name="Platonic_fracturepart43_1"
          geometry={nodes.Platonic_fracturepart43_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart43_2"
          geometry={nodes.Platonic_fracturepart43_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart44" position={[-0.748, -0.214, -0.153]}>
        <mesh
          name="Platonic_fracturepart44_1"
          geometry={nodes.Platonic_fracturepart44_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart44_2"
          geometry={nodes.Platonic_fracturepart44_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart45"
        geometry={nodes.Platonic_fracturepart45.geometry}
        material={materials["Mat.1"]}
        position={[-0.028, -0.17, 0.564]}
      />
      <mesh
        name="Platonic_fracturepart46"
        geometry={nodes.Platonic_fracturepart46.geometry}
        material={materials["Mat.1"]}
        position={[-0.692, 0.068, 0.02]}
      />
      <group name="Platonic_fracturepart47" position={[-0.426, -0.392, 0.458]}>
        <mesh
          name="Platonic_fracturepart47_1"
          geometry={nodes.Platonic_fracturepart47_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart47_2"
          geometry={nodes.Platonic_fracturepart47_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart48" position={[-0.579, 0.411, 0.007]}>
        <mesh
          name="Platonic_fracturepart48_1"
          geometry={nodes.Platonic_fracturepart48_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart48_2"
          geometry={nodes.Platonic_fracturepart48_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart49" position={[-0.062, 0.618, -0.411]}>
        <mesh
          name="Platonic_fracturepart49_1"
          geometry={nodes.Platonic_fracturepart49_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart49_2"
          geometry={nodes.Platonic_fracturepart49_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart5" position={[-0.677, 0.317, 0.244]}>
        <mesh
          name="Platonic_fracturepart5_1"
          geometry={nodes.Platonic_fracturepart5_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart5_2"
          geometry={nodes.Platonic_fracturepart5_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart50"
        geometry={nodes.Platonic_fracturepart50.geometry}
        material={materials["Mat.1"]}
        position={[-0.506, 0.014, -0.284]}
      />
      <group name="Platonic_fracturepart51" position={[0.006, 0.335, -0.689]}>
        <mesh
          name="Platonic_fracturepart51_1"
          geometry={nodes.Platonic_fracturepart51_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart51_2"
          geometry={nodes.Platonic_fracturepart51_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart52" position={[-0.782, -0.05, -0.215]}>
        <mesh
          name="Platonic_fracturepart52_1"
          geometry={nodes.Platonic_fracturepart52_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart52_2"
          geometry={nodes.Platonic_fracturepart52_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart53" position={[-0.718, 0.041, 0.501]}>
        <mesh
          name="Platonic_fracturepart53_1"
          geometry={nodes.Platonic_fracturepart53_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart53_2"
          geometry={nodes.Platonic_fracturepart53_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart54"
        geometry={nodes.Platonic_fracturepart54.geometry}
        material={materials["Mat.1"]}
        position={[-0.188, -0.252, 0.086]}
      />
      <group name="Platonic_fracturepart55" position={[-0.455, 0.51, -0.234]}>
        <mesh
          name="Platonic_fracturepart55_1"
          geometry={nodes.Platonic_fracturepart55_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart55_2"
          geometry={nodes.Platonic_fracturepart55_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart56" position={[-0.5, 0.344, -0.355]}>
        <mesh
          name="Platonic_fracturepart56_1"
          geometry={nodes.Platonic_fracturepart56_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart56_2"
          geometry={nodes.Platonic_fracturepart56_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart57"
        geometry={nodes.Platonic_fracturepart57.geometry}
        material={materials["Mat.1"]}
        position={[-0.131, -0.429, -0.247]}
      />
      <mesh
        name="Platonic_fracturepart58"
        geometry={nodes.Platonic_fracturepart58.geometry}
        material={materials["Mat.1"]}
        position={[-0.501, -0.16, 0.177]}
      />
      <group name="Platonic_fracturepart59" position={[-0.574, 0.386, 0.219]}>
        <mesh
          name="Platonic_fracturepart59_1"
          geometry={nodes.Platonic_fracturepart59_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart59_2"
          geometry={nodes.Platonic_fracturepart59_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart6"
        geometry={nodes.Platonic_fracturepart6.geometry}
        material={materials["Mat.1"]}
        position={[0.01, 0.066, 0.032]}
      />
      <group name="Platonic_fracturepart60" position={[-0.459, -0.526, -0.013]}>
        <mesh
          name="Platonic_fracturepart60_1"
          geometry={nodes.Platonic_fracturepart60_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart60_2"
          geometry={nodes.Platonic_fracturepart60_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart61" position={[0.288, -0.29, -0.52]}>
        <mesh
          name="Platonic_fracturepart61_1"
          geometry={nodes.Platonic_fracturepart61_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart61_2"
          geometry={nodes.Platonic_fracturepart61_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart62"
        geometry={nodes.Platonic_fracturepart62.geometry}
        material={materials["Mat.1"]}
        position={[-0.452, 0.153, -0.239]}
      />
      <group name="Platonic_fracturepart63" position={[-0.482, -0.506, -0.314]}>
        <mesh
          name="Platonic_fracturepart63_1"
          geometry={nodes.Platonic_fracturepart63_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart63_2"
          geometry={nodes.Platonic_fracturepart63_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart64" position={[-0.616, -0.423, -0.277]}>
        <mesh
          name="Platonic_fracturepart64_1"
          geometry={nodes.Platonic_fracturepart64_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart64_2"
          geometry={nodes.Platonic_fracturepart64_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart65" position={[0.063, 0.108, 0.638]}>
        <mesh
          name="Platonic_fracturepart65_1"
          geometry={nodes.Platonic_fracturepart65_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart65_2"
          geometry={nodes.Platonic_fracturepart65_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart66" position={[-0.617, -0.472, 0.105]}>
        <mesh
          name="Platonic_fracturepart66_1"
          geometry={nodes.Platonic_fracturepart66_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart66_2"
          geometry={nodes.Platonic_fracturepart66_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart67" position={[-0.542, 0.569, 0.22]}>
        <mesh
          name="Platonic_fracturepart67_1"
          geometry={nodes.Platonic_fracturepart67_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart67_2"
          geometry={nodes.Platonic_fracturepart67_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart68"
        geometry={nodes.Platonic_fracturepart68.geometry}
        material={materials["Mat.1"]}
        position={[-0.453, -0.431, 0.075]}
      />
      <group name="Platonic_fracturepart69" position={[-0.663, -0.424, 0.233]}>
        <mesh
          name="Platonic_fracturepart69_1"
          geometry={nodes.Platonic_fracturepart69_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart69_2"
          geometry={nodes.Platonic_fracturepart69_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart7" position={[-0.561, 0.547, 0.071]}>
        <mesh
          name="Platonic_fracturepart7_1"
          geometry={nodes.Platonic_fracturepart7_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart7_2"
          geometry={nodes.Platonic_fracturepart7_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart70"
        geometry={nodes.Platonic_fracturepart70.geometry}
        material={materials["Mat.1"]}
        position={[-0.194, -0.513, 0.281]}
      />
      <group name="Platonic_fracturepart71" position={[0.595, 0.293, 0.251]}>
        <mesh
          name="Platonic_fracturepart71_1"
          geometry={nodes.Platonic_fracturepart71_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart71_2"
          geometry={nodes.Platonic_fracturepart71_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart72" position={[-0.716, -0.164, 0.215]}>
        <mesh
          name="Platonic_fracturepart72_1"
          geometry={nodes.Platonic_fracturepart72_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart72_2"
          geometry={nodes.Platonic_fracturepart72_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart73" position={[-0.414, -0.622, 0.308]}>
        <mesh
          name="Platonic_fracturepart73_1"
          geometry={nodes.Platonic_fracturepart73_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart73_2"
          geometry={nodes.Platonic_fracturepart73_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart74"
        geometry={nodes.Platonic_fracturepart74.geometry}
        material={materials["Mat.1"]}
        position={[-0.551, 0.061, -0.286]}
      />
      <mesh
        name="Platonic_fracturepart75"
        geometry={nodes.Platonic_fracturepart75.geometry}
        material={materials["Mat.1"]}
        position={[-0.653, 0.09, -0.25]}
      />
      <group name="Platonic_fracturepart76" position={[-0.737, 0.204, 0.272]}>
        <mesh
          name="Platonic_fracturepart76_1"
          geometry={nodes.Platonic_fracturepart76_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart76_2"
          geometry={nodes.Platonic_fracturepart76_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart77" position={[0.202, 0.279, 0.643]}>
        <mesh
          name="Platonic_fracturepart77_1"
          geometry={nodes.Platonic_fracturepart77_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart77_2"
          geometry={nodes.Platonic_fracturepart77_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart78"
        geometry={nodes.Platonic_fracturepart78.geometry}
        material={materials["Mat.1"]}
        position={[0.069, 0.073, -0.404]}
      />
      <group name="Platonic_fracturepart79" position={[-0.207, 0.365, -0.637]}>
        <mesh
          name="Platonic_fracturepart79_1"
          geometry={nodes.Platonic_fracturepart79_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart79_2"
          geometry={nodes.Platonic_fracturepart79_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart8" position={[-0.459, 0.776, 0.043]}>
        <mesh
          name="Platonic_fracturepart8_1"
          geometry={nodes.Platonic_fracturepart8_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart8_2"
          geometry={nodes.Platonic_fracturepart8_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart80" position={[-0.532, 0.122, -0.58]}>
        <mesh
          name="Platonic_fracturepart80_1"
          geometry={nodes.Platonic_fracturepart80_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart80_2"
          geometry={nodes.Platonic_fracturepart80_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart81" position={[-0.143, 0.606, 0.448]}>
        <mesh
          name="Platonic_fracturepart81_1"
          geometry={nodes.Platonic_fracturepart81_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart81_2"
          geometry={nodes.Platonic_fracturepart81_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart82" position={[-0.683, 0.112, -0.356]}>
        <mesh
          name="Platonic_fracturepart82_1"
          geometry={nodes.Platonic_fracturepart82_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart82_2"
          geometry={nodes.Platonic_fracturepart82_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart83" position={[-0.456, -0.076, -0.529]}>
        <mesh
          name="Platonic_fracturepart83_1"
          geometry={nodes.Platonic_fracturepart83_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart83_2"
          geometry={nodes.Platonic_fracturepart83_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart84"
        geometry={nodes.Platonic_fracturepart84.geometry}
        material={materials["Mat.1"]}
        position={[0.164, -0.261, -0.298]}
      />
      <mesh
        name="Platonic_fracturepart85"
        geometry={nodes.Platonic_fracturepart85.geometry}
        material={materials["Mat.1"]}
        position={[-0.582, -0.143, 0.243]}
      />
      <group name="Platonic_fracturepart86" position={[-0.601, -0.093, 0.565]}>
        <mesh
          name="Platonic_fracturepart86_1"
          geometry={nodes.Platonic_fracturepart86_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart86_2"
          geometry={nodes.Platonic_fracturepart86_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart87"
        geometry={nodes.Platonic_fracturepart87.geometry}
        material={materials["Mat.1"]}
        position={[-0.646, 0.171, -0.152]}
      />
      <mesh
        name="Platonic_fracturepart88"
        geometry={nodes.Platonic_fracturepart88.geometry}
        material={materials["Mat.1"]}
        position={[-0.477, 0.168, -0.529]}
      />
      <group name="Platonic_fracturepart89" position={[-0.772, 0.086, 0.204]}>
        <mesh
          name="Platonic_fracturepart89_1"
          geometry={nodes.Platonic_fracturepart89_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart89_2"
          geometry={nodes.Platonic_fracturepart89_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart9" position={[-0.592, -0.305, 0.267]}>
        <mesh
          name="Platonic_fracturepart9_1"
          geometry={nodes.Platonic_fracturepart9_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart9_2"
          geometry={nodes.Platonic_fracturepart9_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart90" position={[-0.668, -0.124, -0.475]}>
        <mesh
          name="Platonic_fracturepart90_1"
          geometry={nodes.Platonic_fracturepart90_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart90_2"
          geometry={nodes.Platonic_fracturepart90_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart91" position={[-0.038, 0.273, 0.506]}>
        <mesh
          name="Platonic_fracturepart91_1"
          geometry={nodes.Platonic_fracturepart91_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart91_2"
          geometry={nodes.Platonic_fracturepart91_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart92"
        geometry={nodes.Platonic_fracturepart92.geometry}
        material={materials["Mat.1"]}
        position={[0.088, 0.349, -0.205]}
      />
      <mesh
        name="Platonic_fracturepart93"
        geometry={nodes.Platonic_fracturepart93.geometry}
        material={materials["Mat.1"]}
        position={[-0.473, 0.227, 0.046]}
      />
      <mesh
        name="Platonic_fracturepart94"
        geometry={nodes.Platonic_fracturepart94.geometry}
        material={materials["Mat.1"]}
        position={[-0.558, 0.106, 0.064]}
      />
      <group name="Platonic_fracturepart95" position={[-0.038, -0.562, -0.438]}>
        <mesh
          name="Platonic_fracturepart95_1"
          geometry={nodes.Platonic_fracturepart95_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart95_2"
          geometry={nodes.Platonic_fracturepart95_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart96" position={[-0.527, 0.228, 0.413]}>
        <mesh
          name="Platonic_fracturepart96_1"
          geometry={nodes.Platonic_fracturepart96_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart96_2"
          geometry={nodes.Platonic_fracturepart96_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <group name="Platonic_fracturepart97" position={[-0.344, 0.197, -0.504]}>
        <mesh
          name="Platonic_fracturepart97_1"
          geometry={nodes.Platonic_fracturepart97_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart97_2"
          geometry={nodes.Platonic_fracturepart97_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
      <mesh
        name="Platonic_fracturepart98"
        geometry={nodes.Platonic_fracturepart98.geometry}
        material={materials["Mat.1"]}
        position={[-0.217, 0.089, 0.462]}
      />
      <group name="Platonic_fracturepart99" position={[-0.37, 0.407, -0.3]}>
        <mesh
          name="Platonic_fracturepart99_1"
          geometry={nodes.Platonic_fracturepart99_1.geometry}
          material={materials.Mat}
        />
        <mesh
          name="Platonic_fracturepart99_2"
          geometry={nodes.Platonic_fracturepart99_2.geometry}
          material={materials["Mat.1"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/icomore.glb");
